// Room-by-room checklist — single source for /whats-included.
export const CHECKLIST = [
  {
    room: "Kitchen",
    tasks: [
      "Countertops wiped",
      "Backsplash wiped",
      "Sink scrubbed and fixtures shined",
      "Stovetop wiped",
      "Exterior of oven, fridge, dishwasher and microwave wiped",
      "Inside microwave wiped",
      "Cabinet fronts spot-cleaned",
      "Table and chairs wiped",
      "Light switches and door handles wiped",
      "Trash emptied and bag replaced",
      "Floor vacuumed",
      "Floor mopped",
    ],
  },
  {
    room: "Bathrooms",
    tasks: [
      "Toilet cleaned inside, outside and base",
      "Tub scrubbed",
      "Shower walls and door cleaned",
      "Sink and counter cleaned",
      "Faucets and fixtures shined",
      "Mirrors cleaned",
      "Towel bars and toilet paper holder wiped",
      "Cabinet fronts spot-cleaned",
      "Light switches and door handles wiped",
      "Trash emptied",
      "Floor vacuumed",
      "Floor mopped",
    ],
  },
  {
    room: "Bedrooms",
    tasks: [
      "Reachable surfaces dusted",
      "Nightstands and dressers dusted",
      "Beds made (linens changed if left on bed)",
      "Mirrors cleaned",
      "Window sills dusted",
      "Light switches and door handles wiped",
      "Trash emptied",
      "Floor vacuumed or mopped",
    ],
  },
  {
    room: "Living areas and hallways",
    tasks: [
      "Reachable surfaces and shelves dusted",
      "TV stand dusted",
      "Couch cushions straightened",
      "Mirrors and glass tabletops cleaned",
      "Window sills dusted",
      "Light switches and door handles wiped",
      "Stair railings wiped",
      "Stairs vacuumed",
      "Trash emptied",
      "Floors vacuumed",
      "Floors mopped",
    ],
  },
] as const;

export const NOT_INCLUDED = [
  "Exterior windows",
  "Walls",
  "Laundry",
  "Dishes",
  "Pet waste",
  "Biohazards",
];
